---
title: "R Markdown for researchers"
subtitle: "Text writing & data analysis in one document"
author:
- name: Nina Ilchenko
  company: "Data Manager, V-Dem Institute, GU"
date: "June 10, 2020"
output: ioslides_presentation
---

## Overview

> - What is R Markdown?
> - Basic usage
> - Document output formats
> - Common paper features
> - (*) For "big" projects

## R Markdown composites

*User interaction*

- **Markdown**, plain text formatting syntax for web publications ([project's website](https://daringfireball.net/projects/markdown/)). `.md` file format.

- **R** (and some other languages) code embedded in R Markdown document with `.Rmd` file format .

*Engines*

- [{knitr}](https://yihui.org/knitr/), an R package, which executes code and matches its results in the document.

- [Pandoc](https://pandoc.org/), a program converting from and to a number of file formats.

## Basic usage | Markdown

Many tutorials on the web, for instance: [Markdown syntax](https://www.markdownguide.org/basic-syntax/)

Markdown rendering on the fly: [here](https://dillinger.io/)!

[R Markdown examples](https://rmarkdown.rstudio.com/gallery.html)

## Common document output formats | .pdf & .docx

**In RStudio**

- Press ***Knit*** button.

**From R session**

```{r eval=FALSE}
rmarkdown::render('name_of_the_file.Rmd', output_format = "pdf_document")
rmarkdown::render('name_of_the_file.Rmd', output_format = "word_document")
```

## Some elements of papers | Checklist

- Title and abstract

- Footnotes and references

- Equations

- Tables and Figures

- Styling

## Common paper features| References & Footnotes

- footnotes: `Some text[^Text of your footnote]`.

1. Indicate file with references.

2. Use `@tag` and `[@tag]` to cite bibliography items.

3. References are added at the end of the document automatically.

**More**

- `nocite: @*` in YAML header prints all bibliography items.

## Common paper features | Formulas

- Inline

```r
Here are some $\beta$'s in the text.
```

- Separate line

```r
$$y = \beta X + \epsilon$$
```

## Common paper features | Tables

- [{knitr}](https://www.rdocumentation.org/packages/knitr/versions/1.28/topics/kable)'s `kable()` rendering tables in `.pdf` and `.docx`.

- [{flextable}](https://davidgohel.github.io/flextable/articles/overview.html) --- fancy and flexible scientific tables for `.docx` and `.pdf`. Regression tables too.

- [{stargazer}](https://cran.r-project.org/web/packages/stargazer/vignettes/stargazer.pdf) for regression output in `.pdf` (or `.html`). Also supports advanced stat. models, like multilevel modelling.

## Common paper features| Style {.smaller}

**PDF**

- `indent: true` (YAML) for indented paragraphs.

- `fontsize: 12pt` (YAML).

- Use LaTeX syntax in YAML header to add double line spacing (package {setspace}).

**Word**

- You need to create a separate `.docx` document and edit styles there.

```r
---
output:
	word_document:
		reference_docx: style_template.docx
---
```

## Helpful resources {.smaller}

- Xie, Y., Allaire, J. J., & Grolemund, G. (2018). [R markdown: The definitive guide](https://bookdown.org/yihui/rmarkdown/). CRC Press.

- Xie, Y., Dervieux, C. (2020, Forthcoming). [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/). CRC Press.

- [{rticles}](https://github.com/rstudio/rticles) for journal templates (i.e. Taylor & Francis, Elsevier)

- [R Markdown reference guide](https://rstudio.com/wp-content/uploads/2015/03/rmarkdown-reference.pdf?_ga=2.165862332.321186068.1591564116-1090652372.1585899774)

- [R Markdown Gallery](https://rmarkdown.rstudio.com/articles.html)

- [Pandoc (YAML) Metadata Variables](https://pandoc.org/MANUAL.html#metadata-variables)

- [`oxforddown`: An Oxford University Thesis Template for R Markdown](https://ulyngs.github.io/oxforddown/)

- [Miller, Steven V., *An R Markdown Template for Academic Manuscripts*](http://svmiller.com/blog/2016/02/svm-r-markdown-manuscript/)

## Solutions for larger scale projects

- [{bookdown}](https://bookdown.org/home/) for writing books using R Markdown.
- [{drake}](https://books.ropensci.org/drake/) for comprehensive data workflow (building data pipelines).